# Generated by Django 2.0.7 on 2019-11-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'lookapi_category',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='对应的集数')),
                ('link', models.CharField(max_length=255, verbose_name='电影地址')),
            ],
            options={
                'verbose_name': '电影地址',
                'verbose_name_plural': '电影地址',
                'db_table': 'lookapi_tv_link',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='电影名')),
                ('title', models.CharField(max_length=255, verbose_name='电影标题')),
                ('movie_img', models.ImageField(upload_to='all_resource', verbose_name='电影封面')),
                ('brief', models.TextField(max_length=1024, verbose_name='电影简介')),
                ('views', models.IntegerField(default=0, verbose_name='观影人数')),
                ('comments', models.IntegerField(default=0, verbose_name='评论数')),
                ('up_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('down_num', models.IntegerField(default=0, verbose_name='点踩数')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('number', models.IntegerField(default=1, verbose_name='电影集数')),
                ('is_tv', models.BooleanField(default=False, verbose_name='是否为电视剧')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否需要会员')),
                ('category', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='all_resource.Category')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_resource.Link', verbose_name='电影地址')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'lookapi_movie',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'lookapi_tag',
            },
        ),
        migrations.AddField(
            model_name='all_resource',
            name='tag',
            field=models.ManyToManyField(db_constraint=False, related_name='tag', to='all_resource.Tag'),
        ),
    ]
