# Generated by Django 2.0.7 on 2019-11-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_resource',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='all_resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='all_resource.Movie', verbose_name='电影'),
            preserve_default=False,
        ),
    ]
