# Generated by Django 2.0.7 on 2019-11-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_resource', '0002_auto_20191103_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
