# Generated by Django 2.0.7 on 2019-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_resource', '0004_auto_20191109_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_resource',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否需要会员'),
        ),
        migrations.AlterField(
            model_name='all_resource',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
