# Generated by Django 2.0.7 on 2019-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_resource', '0005_auto_20191109_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
